// Live socket validation from s3Dgraphy's connections datamodel — the same
// versioned JSON that drives the Python side (EM 1.5/1.6 connector rules).
// allowed_connections reference *class* names; em_node_classes.json maps the
// runtime node_type strings to their class ancestry (generated by
// introspecting s3dgraphy's Node subclasses; regenerate on datamodel bumps).
import connections from "./assets/s3Dgraphy_connections_datamodel.json";
import nodeClasses from "./assets/em_node_classes.json";

interface EdgeTypeDef {
  name?: string;
  label?: string;
  description?: string;
  allowed_connections?: { source?: string[]; target?: string[] };
}

interface NodeClassDef {
  class: string;
  ancestors: string[];
  description?: string;
}

const EDGE_TYPES = (
  connections as { edge_types: Record<string, EdgeTypeDef> }
).edge_types;
const NODE_CLASSES = nodeClasses as Record<string, NodeClassDef>;

export const GENERIC_EDGE = "generic_connection";

/** Class ancestry for a runtime node_type (always includes "Node"). */
export function ancestorsOf(nodeType: string | undefined): string[] {
  const def = NODE_CLASSES[nodeType ?? ""];
  return def ? def.ancestors : ["Node"];
}

export function classOf(nodeType: string | undefined): string {
  return NODE_CLASSES[nodeType ?? ""]?.class ?? "Node";
}

export function typeDescription(nodeType: string | undefined): string {
  return NODE_CLASSES[nodeType ?? ""]?.description ?? "";
}

function intersects(allowed: string[] | undefined, anc: string[]): boolean {
  if (!allowed || !allowed.length) return false;
  return allowed.some((a) => anc.includes(a));
}

/**
 * Edge types permitted from a source node_type to a target node_type,
 * specific rules only (generic_connection excluded).
 */
export function allowedEdgeTypes(
  sourceType: string | undefined,
  targetType: string | undefined,
): string[] {
  const sa = ancestorsOf(sourceType);
  const ta = ancestorsOf(targetType);
  const out: string[] = [];
  for (const [name, def] of Object.entries(EDGE_TYPES)) {
    if (name === GENERIC_EDGE) continue;
    const ac = def.allowed_connections;
    if (!ac) continue;
    if (intersects(ac.source, sa) && intersects(ac.target, ta)) out.push(name);
  }
  return out;
}

export type ConnectValidity = "valid" | "generic" | "invalid";

export function connectValidity(
  sourceType: string | undefined,
  targetType: string | undefined,
): ConnectValidity {
  if (allowedEdgeTypes(sourceType, targetType).length) return "valid";
  const g = EDGE_TYPES[GENERIC_EDGE]?.allowed_connections;
  const ok =
    g &&
    intersects(g.source, ancestorsOf(sourceType)) &&
    intersects(g.target, ancestorsOf(targetType));
  return ok ? "generic" : "invalid";
}

export function edgeTypeLabel(edgeType: string): string {
  return EDGE_TYPES[edgeType]?.label ?? edgeType;
}

export function edgeTypeDescription(edgeType: string): string {
  return EDGE_TYPES[edgeType]?.description ?? "";
}

/** node_types whose class ancestry includes the given class name. */
export function typesOfClass(className: string): string[] {
  return Object.keys(NODE_CLASSES).filter((t) =>
    NODE_CLASSES[t].ancestors.includes(className),
  );
}

export function isGroupType(nodeType: string | undefined): boolean {
  return ancestorsOf(nodeType).includes("GroupNode");
}

export function isStratigraphicType(nodeType: string | undefined): boolean {
  return ancestorsOf(nodeType).includes("StratigraphicNode");
}
